# -*- coding: utf-8 -*-
"""GenAI_Lab11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15JDN7KtOCvPkz39fnCHBJQpeLMVXDWrn
"""

pip install langchain faiss-cpu sentence-transformers pillow transformers

# -----------------------------
# Install Required Libraries
# -----------------------------
import subprocess, sys

packages = [
    "sentence-transformers",
    "faiss-cpu",
    "pillow",
    "numpy",
    "transformers"
]

for p in packages:
    subprocess.check_call([sys.executable, "-m", "pip", "install", p])


# -----------------------------
# Imports
# -----------------------------
import urllib.request
from PIL import Image
import numpy as np
import faiss
from sentence_transformers import SentenceTransformer
from transformers import pipeline


# -----------------------------
# Step 1: Download Images
# -----------------------------
def download_image(url, filename):
    req = urllib.request.Request(
        url,
        headers={"User-Agent": "Mozilla/5.0"}
    )
    with urllib.request.urlopen(req) as response:
        with open(filename, "wb") as f:
            f.write(response.read())


image_urls = {
    "diagram.png": "https://images.unsplash.com/photo-1555949963-aa79dcee981c",
    "login_ui.png": "https://images.unsplash.com/photo-1563986768609-322da13575f3"
}

for filename, url in image_urls.items():
    download_image(url, filename)

print("Images downloaded successfully")


# -----------------------------
# Step 2: Text Documents
# -----------------------------
texts = [
    "This diagram explains the architecture of a neural network.",
    "This screenshot shows a login interface used in applications.",
    "Tables in reports show structured financial data."
]


# -----------------------------
# Step 3: Load Multimodal Model
# -----------------------------
model = SentenceTransformer("clip-ViT-B-32")


# -----------------------------
# Step 4: Create Embeddings
# -----------------------------
text_embeddings = model.encode(texts)

image_paths = ["diagram.png", "login_ui.png"]
image_embeddings = []

for path in image_paths:
    img = Image.open(path).convert("RGB")
    emb = model.encode(img)
    image_embeddings.append(emb)

image_embeddings = np.array(image_embeddings)


# -----------------------------
# Step 5: Combine Embeddings
# -----------------------------
all_embeddings = np.vstack([text_embeddings, image_embeddings])


# -----------------------------
# Step 6: Create Vector DB
# -----------------------------
dimension = all_embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)
index.add(all_embeddings)

print("Vector database created")


# -----------------------------
# Step 7: Query
# -----------------------------
query = "Explain neural network architecture diagram"

query_embedding = model.encode([query])

k = 3
distances, indices = index.search(query_embedding, k)


# -----------------------------
# Step 8: Retrieve Context
# -----------------------------
context = ""

print("\nRetrieved Information:\n")

for i in indices[0]:

    if i < len(texts):
        print("Text:", texts[i])
        context += texts[i] + "\n"

    else:
        img_index = i - len(texts)
        print("Image:", image_paths[img_index])
        context += f"Image file: {image_paths[img_index]}\n"


# -----------------------------
# Step 9: Generation (LLM)
# -----------------------------
generator = pipeline("text-generation", model="gpt2")

prompt = f"""
Use the following retrieved information to answer the question.

Context:
{context}

Question: {query}

Answer:
"""

response = generator(prompt, max_length=200)

print("\nGenerated Answer:\n")
print(response[0]["generated_text"])

# -----------------------------
# Install Libraries
# -----------------------------
import subprocess, sys

packages = [
    "sentence-transformers",
    "faiss-cpu",
    "numpy",
    "transformers"
]

for p in packages:
    subprocess.check_call([sys.executable, "-m", "pip", "install", p])


# -----------------------------
# Imports
# -----------------------------
import numpy as np
import faiss
from sentence_transformers import SentenceTransformer
from transformers import pipeline


# -----------------------------
# Step 1: Create Knowledge Sources
# -----------------------------

internal_docs = [
    "Employees are entitled to 20 days of paid leave per year.",
    "Travel reimbursement must be submitted within 7 days.",
    "The company follows a hybrid work policy."
]

faq_docs = [
    "Shipping usually takes 3 to 5 business days.",
    "Refunds are available within 30 days of purchase.",
    "Customer support is available 24 hours via email."
]


# -----------------------------
# Step 2: Load Embedding Model
# -----------------------------
model = SentenceTransformer("all-MiniLM-L6-v2")


# -----------------------------
# Step 3: Create Embeddings
# -----------------------------
internal_embeddings = model.encode(internal_docs)
faq_embeddings = model.encode(faq_docs)


# -----------------------------
# Step 4: Create Vector Databases
# -----------------------------
dim = internal_embeddings.shape[1]

internal_index = faiss.IndexFlatL2(dim)
internal_index.add(np.array(internal_embeddings))

faq_index = faiss.IndexFlatL2(dim)
faq_index.add(np.array(faq_embeddings))

print("Vector databases created")


# -----------------------------
# Step 5: Agent Router
# -----------------------------
def router(query):

    query = query.lower()

    if "employee" in query or "policy" in query or "leave" in query:
        return "internal"

    elif "shipping" in query or "refund" in query or "support" in query:
        return "faq"

    else:
        return "faq"


# -----------------------------
# Step 6: User Query
# -----------------------------
query = "What is the employee leave policy?"

print("\nUser Query:", query)


# -----------------------------
# Step 7: Agent Chooses Source
# -----------------------------
source = router(query)

print("Agent selected source:", source)


# -----------------------------
# Step 8: Retrieval
# -----------------------------
query_embedding = model.encode([query])

if source == "internal":

    distances, indices = internal_index.search(query_embedding, 2)

    context = ""
    for i in indices[0]:
        context += internal_docs[i] + "\n"

else:

    distances, indices = faq_index.search(query_embedding, 2)

    context = ""
    for i in indices[0]:
        context += faq_docs[i] + "\n"


print("\nRetrieved Context:\n")
print(context)


# -----------------------------
# Step 9: Generation
# -----------------------------
generator = pipeline("text-generation", model="gpt2")

prompt = f"""
Use the following context to answer the question.

Context:
{context}

Question: {query}

Answer:
"""

response = generator(prompt, max_length=150)

print("\nGenerated Answer:\n")
print(response[0]["generated_text"])

# -----------------------------
# Install Libraries
# -----------------------------
import subprocess, sys

packages = [
    "sentence-transformers",
    "faiss-cpu",
    "numpy",
    "transformers"
]

for p in packages:
    subprocess.check_call([sys.executable, "-m", "pip", "install", p])


# -----------------------------
# Imports
# -----------------------------
import numpy as np
import faiss
from sentence_transformers import SentenceTransformer
from transformers import pipeline


# -----------------------------
# Step 1: Create Knowledge Sources
# -----------------------------

internal_docs = [
    "Employees are entitled to 20 days of paid leave per year.",
    "Travel reimbursement must be submitted within 7 days.",
    "The company follows a hybrid work policy."
]

faq_docs = [
    "Shipping usually takes 3 to 5 business days.",
    "Refunds are available within 30 days of purchase.",
    "Customer support is available 24 hours via email."
]


# -----------------------------
# Step 2: Load Embedding Model
# -----------------------------
model = SentenceTransformer("all-MiniLM-L6-v2")


# -----------------------------
# Step 3: Create Embeddings
# -----------------------------
internal_embeddings = model.encode(internal_docs)
faq_embeddings = model.encode(faq_docs)


# -----------------------------
# Step 4: Create Vector Databases
# -----------------------------
dim = internal_embeddings.shape[1]

internal_index = faiss.IndexFlatL2(dim)
internal_index.add(np.array(internal_embeddings))

faq_index = faiss.IndexFlatL2(dim)
faq_index.add(np.array(faq_embeddings))

print("Vector databases created")


# -----------------------------
# Step 5: Agent Router
# -----------------------------
def router(query):

    query = query.lower()

    if "employee" in query or "policy" in query or "leave" in query:
        return "internal"

    elif "shipping" in query or "refund" in query or "support" in query:
        return "faq"

    else:
        return "faq"


# -----------------------------
# Step 6: User Query
# -----------------------------
query = "What is the employee leave policy?"

print("\nUser Query:", query)


# -----------------------------
# Step 7: Agent Chooses Source
# -----------------------------
source = router(query)

print("Agent selected source:", source)


# -----------------------------
# Step 8: Retrieval
# -----------------------------
query_embedding = model.encode([query])

if source == "internal":

    distances, indices = internal_index.search(query_embedding, 2)

    context = ""
    for i in indices[0]:
        context += internal_docs[i] + "\n"

else:

    distances, indices = faq_index.search(query_embedding, 2)

    context = ""
    for i in indices[0]:
        context += faq_docs[i] + "\n"


print("\nRetrieved Context:\n")
print(context)


# -----------------------------
# Step 9: Generation
# -----------------------------
generator = pipeline("text-generation", model="gpt2")

prompt = f"""
Use the following context to answer the question.

Context:
{context}

Question: {query}

Answer:
"""

response = generator(prompt, max_length=150)

print("\nGenerated Answer:\n")
print(response[0]["generated_text"])