# -*- coding: utf-8 -*-
"""GenAI_Lab9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b1v4UC-_WHbeSaclPQuSb2o3FSvzDsbS
"""

!pip install --upgrade transformers datasets torchaudio librosa

"""## Zero-Shot audio classification"""

from transformers import pipeline

classifier = pipeline(
    task="zero-shot-audio-classification",
    model="laion/clap-htsat-unfused"
)

labels = ["happy", "sad", "angry", "neutral"]

result = classifier(
    "audio.wav",   # your audio file
    candidate_labels=labels
)

print(result)

"""## Automatic Speech Recognition (ASR)"""

import librosa
from transformers import pipeline

audio, sr = librosa.load("audio.wav", sr=16000)

asr = pipeline("automatic-speech-recognition", model="openai/whisper-tiny")

result = asr({"array": audio, "sampling_rate": sr})

print("Transcription:", result["text"])

"""## Text-to-Speech (TTS)"""

from transformers import pipeline

tts = pipeline("text-to-speech", model="facebook/mms-tts-eng")

output = tts("Hello, this is a test.")

import soundfile as sf
sf.write("output.wav", output["audio"], output["sampling_rate"])