# -*- coding: utf-8 -*-
"""GenAI_LangChain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gcy_ZcYuBiPJDD0WTSB1mUTiNuLVa0fx
"""

!pip install -U langchain langchain-core langchain-community langchain-groq

import os
from getpass import getpass

# Hidden input field
groq_key = getpass("Enter your GROQ API key: ")

# Store in environment variable for LangChain
os.environ["GROQ_API_KEY"] = groq_key

from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

# Use a CURRENT Groq model
llm = ChatGroq(
    model="llama-3.1-8b-instant",
    temperature=0
)

prompt = ChatPromptTemplate.from_template(
    "Explain {topic} in 2 to 3 sentences."
)

chain = prompt | llm | StrOutputParser()

print(chain.invoke({"topic": "Machine language"}))

"""Lang Graph"""

pip install langgraph transformers torch

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from langgraph.graph import StateGraph, END
from typing import TypedDict

# Load model
model_name = "google/flan-t5-small"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# Proper LangGraph state schema
class State(TypedDict):
    topic: str
    answer: str

# Node function
def explain_node(state: State):
    topic = state["topic"]
    prompt = f"Explain {topic} in 2 to 3 sentences."

    inputs = tokenizer(prompt, return_tensors="pt")
    outputs = model.generate(**inputs, max_new_tokens=120)

    answer = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return {"answer": answer}   # IMPORTANT: return partial state

# Build graph
graph = StateGraph(State)

graph.add_node("explain", explain_node)
graph.set_entry_point("explain")
graph.add_edge("explain", END)

app = graph.compile()

# Run
result = app.invoke({"topic": "Machine language"})
print(result["answer"])

"""Lang Flow"""

!pip install -U langflow

!python -m langflow run --host 0.0.0.0 --port 7860 --log-level info

from google.colab import output
output.serve_kernel_port_as_window(7860)