# -*- coding: utf-8 -*-
"""GenAI_Groq.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jcNdjtaeB6ZYfMrPa4dPo-qopA1tGHOb
"""

pip install langchain langchain_groq

import os
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate

os.environ["GROQ_API_KEY"] = "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"

llm = ChatGroq(model="llama-3.1-8b-instant")

prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a helpful assistant"),
    ("human", "{question}")
])

chain = prompt | llm

result = chain.invoke({
    "question": "Write a short, suspenseful thriller story about a lost boy trapped in a haunted mansion as he searches for his missing parents."
})

print(result.content)

